#########################################################
# Please refer to the README before changing this file! #
#########################################################

# MAVLink Interface
DEVICE_STR: "/dev/ttyAMA0"
BAUD_RATE: 115200
MESSAGE_RATE_MAX: 30  # in Hz

# AI Model Settings
MODEL_PATH: "./BEST.blob"
ISP_SCALE:
  - 1  # numerator
  - 3  # denominator

# Obstacle Detection
HOST_SIDE: True
GRID_NUM:
  - 5  # H
  - 5  # W
# BELOW: Only work with host side detection
GRID_THRESHOLD: 0.1
MASK_THRESHOLD: 0.9

# Ignore Area
IGNORE_GRIDS:
  - 1  # Upper
  - 1  # Lower
  - 0  # Left
  - 0  # Right

# Stereo Mode
EXTENDED_DISPARITY: False
SUBPIXEL: True

# Depth Thresholds
CONFIDENCE_THRESHOLD: 190  # 0-255
MIN_DISTANCE: 0.35  # in m
MAX_DISTANCE: 35  # in m

# Depth Post Processing
# WARNING: MAY SIGNIFICANTLY INCREASE DEPTH MAP'S LATENCY!!!
DECIMATION_FACTOR: 1
SPECKLE_FILTER: False
TEMPORAL_FILTER: False
SPATIAL_FILTER: False

# Other Settings
USE_INTRINSIC: True
